CREATE PROCEDURE CREAR_AFILIADO (
    PRIMER_NOMBRE VARCHAR(50),
    SEGUNDO_NOMBRE VARCHAR(50),
    PRIMER_APELLIDO VARCHAR(50),
    SEGUNDO_APELLIDO VARCHAR(50),
    CALLE VARCHAR(50),
    AVENIDA VARCHAR(50),
    NUM_CASA VARCHAR(10),
    CIUDAD VARCHAR(50),
    DEPARTAMENTO VARCHAR(50),
    REFERENCIA VARCHAR(50),
    CORREO_PRIMARIO VARCHAR(50),
    CORREO_SECUNDARIO VARCHAR(50),
    FECHA_NACIMIENTO DATE,
    USUARIO_CREADOR VARCHAR(30))
AS
DECLARE VARIABLE v_codigo VARCHAR(30);
BEGIN
	
    v_codigo = 'AF-' || LPAD(NEXT VALUE FOR SEQ_AFILIADO, 5, '0');

    INSERT INTO AFILIADO (CODIGO, PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO,
                          CALLE, AVENIDA, NUM_CASA, CIUDAD, DEPARTAMENTO, REFERENCIA, CORREO_PRIMARIO,
                          CORREO_SECUNDARIO, FECHA_NACIMIENTO, FECHA_INICIO, USUARIO_CREADOR)
    VALUES (:v_codigo, :PRIMER_NOMBRE, :SEGUNDO_NOMBRE, :PRIMER_APELLIDO, :SEGUNDO_APELLIDO,
            :CALLE, :AVENIDA, :NUM_CASA, :CIUDAD, :DEPARTAMENTO, :REFERENCIA, :CORREO_PRIMARIO,
            :CORREO_SECUNDARIO, :FECHA_NACIMIENTO, CURRENT_TIMESTAMP, :USUARIO_CREADOR);
END;

CREATE PROCEDURE INSERTAR_TELEFONOS (
TELEFONO VARCHAR(30),
AFILIADO_CODIGO VARCHAR(30)
)
AS
BEGIN
	INSERT INTO TELEFONOS_AFILIADO (TELEFONO, AFILIADO_CODIGO) VALUES (:TELEFONO, :AFILIADO_CODIGO);
END;


CREATE PROCEDURE LEER_AFILIADO (
    CODIGO VARCHAR(30))
RETURNS (
    PRIMER_NOMBRE VARCHAR(50),
    SEGUNDO_NOMBRE VARCHAR(50),
    PRIMER_APELLIDO VARCHAR(50),
    SEGUNDO_APELLIDO VARCHAR(50),
    CALLE VARCHAR(50),
    AVENIDA VARCHAR(50),
    NUM_CASA VARCHAR(10),
    CIUDAD VARCHAR(50),
    DEPARTAMENTO VARCHAR(50),
    REFERENCIA VARCHAR(50),
    CORREO_PRIMARIO VARCHAR(50),
    CORREO_SECUNDARIO VARCHAR(50),
    FECHA_NACIMIENTO DATE,
    FECHA_INICIO DATE,
    USUARIO_CREADOR VARCHAR(30))
AS
BEGIN
    FOR SELECT PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO,
              CALLE, AVENIDA, NUM_CASA, CIUDAD, DEPARTAMENTO, REFERENCIA,
              CORREO_PRIMARIO, CORREO_SECUNDARIO, FECHA_NACIMIENTO, FECHA_INICIO, USUARIO_CREADOR
        FROM AFILIADO
        WHERE CODIGO = :CODIGO
        INTO :PRIMER_NOMBRE, :SEGUNDO_NOMBRE, :PRIMER_APELLIDO, :SEGUNDO_APELLIDO,
             :CALLE, :AVENIDA, :NUM_CASA, :CIUDAD, :DEPARTAMENTO, :REFERENCIA,
             :CORREO_PRIMARIO, :CORREO_SECUNDARIO, :FECHA_NACIMIENTO, :FECHA_INICIO, :USUARIO_CREADOR
    DO
        SUSPEND;
END;


CREATE PROCEDURE LEER_AFILIADOS 
RETURNS (
    CODIGO VARCHAR(30),
    PRIMER_NOMBRE VARCHAR(50),
    SEGUNDO_NOMBRE VARCHAR(50),
    PRIMER_APELLIDO VARCHAR(50),
    SEGUNDO_APELLIDO VARCHAR(50),
    CALLE VARCHAR(50),
    AVENIDA VARCHAR(50),
    NUM_CASA VARCHAR(10),
    CIUDAD VARCHAR(50),
    DEPARTAMENTO VARCHAR(50),
    REFERENCIA VARCHAR(50),
    CORREO_PRIMARIO VARCHAR(50),
    CORREO_SECUNDARIO VARCHAR(50),
    FECHA_NACIMIENTO DATE,
    FECHA_INICIO DATE,
    USUARIO_CREADOR VARCHAR(30))
AS
BEGIN
    FOR SELECT CODIGO, PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO,
              CALLE, AVENIDA, NUM_CASA, CIUDAD, DEPARTAMENTO, REFERENCIA,
              CORREO_PRIMARIO, CORREO_SECUNDARIO, FECHA_NACIMIENTO, FECHA_INICIO, USUARIO_CREADOR
        FROM AFILIADO
        INTO :CODIGO, :PRIMER_NOMBRE, :SEGUNDO_NOMBRE, :PRIMER_APELLIDO, :SEGUNDO_APELLIDO,
             :CALLE, :AVENIDA, :NUM_CASA, :CIUDAD, :DEPARTAMENTO, :REFERENCIA,
             :CORREO_PRIMARIO, :CORREO_SECUNDARIO, :FECHA_NACIMIENTO, :FECHA_INICIO, :USUARIO_CREADOR
    DO
        SUSPEND;
END;


CREATE PROCEDURE ACTUALIZAR_AFILIADO (
    CODIGO VARCHAR(30),
    PRIMER_NOMBRE VARCHAR(50),
    SEGUNDO_NOMBRE VARCHAR(50),
    PRIMER_APELLIDO VARCHAR(50),
    SEGUNDO_APELLIDO VARCHAR(50),
    CALLE VARCHAR(50),
    AVENIDA VARCHAR(50),
    NUM_CASA VARCHAR(10),
    CIUDAD VARCHAR(50),
    DEPARTAMENTO VARCHAR(50),
    REFERENCIA VARCHAR(50),
    CORREO_PRIMARIO VARCHAR(50),
    CORREO_SECUNDARIO VARCHAR(50),
    FECHA_NACIMIENTO DATE)
AS
BEGIN
    UPDATE AFILIADO
    SET PRIMER_NOMBRE = :PRIMER_NOMBRE,
        SEGUNDO_NOMBRE = :SEGUNDO_NOMBRE,
        PRIMER_APELLIDO = :PRIMER_APELLIDO,
        SEGUNDO_APELLIDO = :SEGUNDO_APELLIDO,
        CALLE = :CALLE,
        AVENIDA = :AVENIDA,
        NUM_CASA = :NUM_CASA,
        CIUDAD = :CIUDAD,
        DEPARTAMENTO = :DEPARTAMENTO,
        REFERENCIA = :REFERENCIA,
        CORREO_PRIMARIO = :CORREO_PRIMARIO,
        CORREO_SECUNDARIO = :CORREO_SECUNDARIO,
        FECHA_NACIMIENTO = :FECHA_NACIMIENTO
    WHERE CODIGO = :CODIGO;
END;


CREATE PROCEDURE ELIMINAR_AFILIADO (
    CODIGO VARCHAR(30))
AS
BEGIN
    DELETE FROM AFILIADO
    WHERE CODIGO = :CODIGO;
END;