/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mi_cooperativa_hv;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author fefov
 */
public class Pantalla_Principal extends javax.swing.JPanel {

    private static String User_Actual;
    private final List<String> telefonos;
    private List<Afiliados_obj> AfiliadosList;
    private final DefaultListModel<String> AfiliadosListModel;
    private final DefaultListModel<String> telefonosListModel;

    /**
     * Creates new form Pantalla_Principal
     */
    public Pantalla_Principal() {
        AfiliadosList = new ArrayList<>();
        AfiliadosListModel = new DefaultListModel<>();
        telefonosListModel = new DefaultListModel<>();
        telefonos = new ArrayList<>();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        valid_user = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        user_text = new javax.swing.JTextField();
        pass_text = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        CERRAR_SESION_BTT = new javax.swing.JButton();
        GESTION_CUENTAS_BTT = new javax.swing.JButton();
        GESTION_AFILIADOS_BTT = new javax.swing.JButton();
        GESTION_PRESTAMOS_BTT = new javax.swing.JButton();
        GESTION_PAGOS_BTT = new javax.swing.JButton();
        CIERRA_MENSUAL_BTT = new javax.swing.JButton();
        REPORTES_BTT = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        CONSULTAR_CUENTAS = new javax.swing.JButton();
        CONSULTAR_PRESTAMOS = new javax.swing.JButton();
        CONSULTAR_DIVIDENDOS = new javax.swing.JButton();
        Informacion_personal = new javax.swing.JButton();
        CERRAR_CESION_BTT2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        valid_user1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        user_text1 = new javax.swing.JTextField();
        pass_text1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        CERRAR_CESION_BTT1 = new javax.swing.JButton();
        GESTION_CUENTAS_BTT1 = new javax.swing.JButton();
        GESTION_AFILIADOS_BTT1 = new javax.swing.JButton();
        GESTION_PRESTAMOS_BTT1 = new javax.swing.JButton();
        GESTION_PAGOS_BTT1 = new javax.swing.JButton();
        CIERRA_MENSUAL_BTT1 = new javax.swing.JButton();
        REPORTES_BTT1 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        CONSULTAR_CUENTAS1 = new javax.swing.JButton();
        CONSULTAR_PRESTAMOS1 = new javax.swing.JButton();
        CONSULTAR_DIVIDENDOS1 = new javax.swing.JButton();
        Informacion_personal1 = new javax.swing.JButton();
        CERRAR_CESION_BTT3 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        InPane4 = new javax.swing.JPanel();
        PrimerNombre1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        SegundoNombre1 = new javax.swing.JTextField();
        PrimerApellido1 = new javax.swing.JTextField();
        SegundoApellido1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        Calle1 = new javax.swing.JTextField();
        NumCasa1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        Avenida1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        Depto1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        Reff1 = new javax.swing.JTextField();
        Ciudad1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        InPane5 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        Correo3 = new javax.swing.JTextField();
        Correo4 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        FechaNacimiento_cb1 = new de.wannawork.jcalendar.JCalendarComboBox();
        InPane6 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        Telefono1 = new javax.swing.JTextField();
        AGREGAR_TELEFONO1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaTeleonos1 = new javax.swing.JList<>();
        AGREGAR_AFILIADO_BTT1 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        InPane1 = new javax.swing.JPanel();
        PrimerNombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SegundoNombre = new javax.swing.JTextField();
        PrimerApellido = new javax.swing.JTextField();
        SegundoApellido = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Calle = new javax.swing.JTextField();
        NumCasa = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Avenida = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Depto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Reff = new javax.swing.JTextField();
        Ciudad = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        InPane2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Correo1 = new javax.swing.JTextField();
        Correo2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        FechaNacimiento_cb = new de.wannawork.jcalendar.JCalendarComboBox();
        InPane3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        Telefono = new javax.swing.JTextField();
        AGREGAR_TELEFONO = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaTeleonos = new javax.swing.JList<>();
        AGREGAR_AFILIADO_BTT = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel6 = new javax.swing.JPanel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jPanel7 = new javax.swing.JPanel();
        jToggleButton3 = new javax.swing.JToggleButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaAfiliados = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jToggleButton4 = new javax.swing.JToggleButton();

        setMinimumSize(new java.awt.Dimension(650, 535));
        setPreferredSize(new java.awt.Dimension(650, 500));
        setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        valid_user.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valid_user.setText("Ingresar");
        valid_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valid_userActionPerformed(evt);
            }
        });
        jPanel1.add(valid_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 120, 40));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 36)); // NOI18N
        jLabel1.setText("MI COOPERATIVA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 310, 35));

        user_text.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(user_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 180, 30));

        pass_text.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(pass_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 180, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Usuario:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Contraseña:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, 20));

        add(jPanel1, "card2");

        jPanel2.setPreferredSize(new java.awt.Dimension(600, 500));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 36)); // NOI18N
        jLabel4.setText("Menu Principal");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 250, 35));

        CERRAR_SESION_BTT.setText("CERRAR SESION");
        CERRAR_SESION_BTT.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        CERRAR_SESION_BTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CERRAR_SESION_BTTActionPerformed(evt);
            }
        });
        jPanel2.add(CERRAR_SESION_BTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 180, 30));

        GESTION_CUENTAS_BTT.setText("GESTION DE CUENTAS");
        GESTION_CUENTAS_BTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GESTION_CUENTAS_BTTActionPerformed(evt);
            }
        });
        jPanel2.add(GESTION_CUENTAS_BTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 180, 30));

        GESTION_AFILIADOS_BTT.setText("GESTION DE AFILIADOS");
        GESTION_AFILIADOS_BTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GESTION_AFILIADOS_BTTActionPerformed(evt);
            }
        });
        jPanel2.add(GESTION_AFILIADOS_BTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 180, 30));

        GESTION_PRESTAMOS_BTT.setText("GESTION DE PRESTAMOS");
        GESTION_PRESTAMOS_BTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GESTION_PRESTAMOS_BTTActionPerformed(evt);
            }
        });
        jPanel2.add(GESTION_PRESTAMOS_BTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 180, 30));

        GESTION_PAGOS_BTT.setText("GESTION DE PAGOS");
        GESTION_PAGOS_BTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GESTION_PAGOS_BTTActionPerformed(evt);
            }
        });
        jPanel2.add(GESTION_PAGOS_BTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 180, 30));

        CIERRA_MENSUAL_BTT.setText("CIERRRE MENSUAL");
        CIERRA_MENSUAL_BTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CIERRA_MENSUAL_BTTActionPerformed(evt);
            }
        });
        jPanel2.add(CIERRA_MENSUAL_BTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 180, 30));

        REPORTES_BTT.setText("REPORTES");
        REPORTES_BTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REPORTES_BTTActionPerformed(evt);
            }
        });
        jPanel2.add(REPORTES_BTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 180, 30));

        add(jPanel2, "card3");

        jPanel3.setMaximumSize(new java.awt.Dimension(600, 500));
        jPanel3.setPreferredSize(new java.awt.Dimension(600, 500));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 28)); // NOI18N
        jLabel5.setText("Menu Principal");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 210, 35));

        CONSULTAR_CUENTAS.setText("GESTION DE CUENTAS");
        CONSULTAR_CUENTAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONSULTAR_CUENTASActionPerformed(evt);
            }
        });
        jPanel3.add(CONSULTAR_CUENTAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 220, 30));

        CONSULTAR_PRESTAMOS.setText("GESTION DE PRESTAMOS");
        CONSULTAR_PRESTAMOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONSULTAR_PRESTAMOSActionPerformed(evt);
            }
        });
        jPanel3.add(CONSULTAR_PRESTAMOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 220, 30));

        CONSULTAR_DIVIDENDOS.setText("CONSULTAR_DIVIDENDOS");
        CONSULTAR_DIVIDENDOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONSULTAR_DIVIDENDOSActionPerformed(evt);
            }
        });
        jPanel3.add(CONSULTAR_DIVIDENDOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 220, 30));

        Informacion_personal.setText("INFORMACION PERSONAL");
        Informacion_personal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Informacion_personalActionPerformed(evt);
            }
        });
        jPanel3.add(Informacion_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 220, 30));

        CERRAR_CESION_BTT2.setText("CERRAR CESION");
        CERRAR_CESION_BTT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CERRAR_CESION_BTT2ActionPerformed(evt);
            }
        });
        jPanel3.add(CERRAR_CESION_BTT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 220, 30));

        add(jPanel3, "card4");

        jPanel4.setMinimumSize(new java.awt.Dimension(650, 535));
        jPanel4.setPreferredSize(new java.awt.Dimension(650, 500));
        jPanel4.setLayout(new java.awt.CardLayout());

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        valid_user1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valid_user1.setText("Ingresar");
        valid_user1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valid_user1ActionPerformed(evt);
            }
        });
        jPanel9.add(valid_user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 120, 40));

        jLabel20.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 36)); // NOI18N
        jLabel20.setText("MI COOPERATIVA");
        jPanel9.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 310, 35));

        user_text1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel9.add(user_text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 180, 30));

        pass_text1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel9.add(pass_text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 180, 30));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("Usuario:");
        jPanel9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("Contraseña:");
        jPanel9.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, 20));

        jPanel4.add(jPanel9, "card2");

        jPanel10.setPreferredSize(new java.awt.Dimension(600, 500));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 36)); // NOI18N
        jLabel24.setText("Menu Principal");
        jPanel10.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 250, 35));

        CERRAR_CESION_BTT1.setText("CERRAR CESION");
        CERRAR_CESION_BTT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CERRAR_CESION_BTT1ActionPerformed(evt);
            }
        });
        jPanel10.add(CERRAR_CESION_BTT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 190, 30));

        GESTION_CUENTAS_BTT1.setText("GESTION DE CUENTAS");
        GESTION_CUENTAS_BTT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GESTION_CUENTAS_BTT1ActionPerformed(evt);
            }
        });
        jPanel10.add(GESTION_CUENTAS_BTT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 180, 30));

        GESTION_AFILIADOS_BTT1.setText("GESTION DE AFILIADOS");
        GESTION_AFILIADOS_BTT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GESTION_AFILIADOS_BTT1ActionPerformed(evt);
            }
        });
        jPanel10.add(GESTION_AFILIADOS_BTT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 180, 30));

        GESTION_PRESTAMOS_BTT1.setText("GESTION DE PRESTAMOS");
        GESTION_PRESTAMOS_BTT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GESTION_PRESTAMOS_BTT1ActionPerformed(evt);
            }
        });
        jPanel10.add(GESTION_PRESTAMOS_BTT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 180, 30));

        GESTION_PAGOS_BTT1.setText("GESTION DE PAGOS");
        GESTION_PAGOS_BTT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GESTION_PAGOS_BTT1ActionPerformed(evt);
            }
        });
        jPanel10.add(GESTION_PAGOS_BTT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 180, 30));

        CIERRA_MENSUAL_BTT1.setText("CIERRRE MENSUAL");
        CIERRA_MENSUAL_BTT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CIERRA_MENSUAL_BTT1ActionPerformed(evt);
            }
        });
        jPanel10.add(CIERRA_MENSUAL_BTT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 180, 30));

        REPORTES_BTT1.setText("REPORTES");
        REPORTES_BTT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REPORTES_BTT1ActionPerformed(evt);
            }
        });
        jPanel10.add(REPORTES_BTT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 180, 30));

        jPanel4.add(jPanel10, "card3");

        jPanel11.setMaximumSize(new java.awt.Dimension(600, 500));
        jPanel11.setPreferredSize(new java.awt.Dimension(600, 500));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 24)); // NOI18N
        jLabel25.setText("Menu Principal");
        jPanel11.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 200, 35));

        CONSULTAR_CUENTAS1.setText("GESTION DE CUENTAS");
        CONSULTAR_CUENTAS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONSULTAR_CUENTAS1ActionPerformed(evt);
            }
        });
        jPanel11.add(CONSULTAR_CUENTAS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 190, 30));

        CONSULTAR_PRESTAMOS1.setText("GESTION DE PRESTAMOS");
        CONSULTAR_PRESTAMOS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONSULTAR_PRESTAMOS1ActionPerformed(evt);
            }
        });
        jPanel11.add(CONSULTAR_PRESTAMOS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 190, 30));

        CONSULTAR_DIVIDENDOS1.setText("CONSULTAR_DIVIDENDOS");
        CONSULTAR_DIVIDENDOS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONSULTAR_DIVIDENDOS1ActionPerformed(evt);
            }
        });
        jPanel11.add(CONSULTAR_DIVIDENDOS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 190, 30));

        Informacion_personal1.setText("INFORMACION PERSONAL");
        Informacion_personal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Informacion_personal1ActionPerformed(evt);
            }
        });
        jPanel11.add(Informacion_personal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 190, 30));

        CERRAR_CESION_BTT3.setText("CERRAR CESION");
        CERRAR_CESION_BTT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CERRAR_CESION_BTT3ActionPerformed(evt);
            }
        });
        jPanel11.add(CERRAR_CESION_BTT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 190, 30));

        jPanel4.add(jPanel11, "card4");

        jTabbedPane2.setPreferredSize(new java.awt.Dimension(600, 500));

        jPanel12.setMinimumSize(new java.awt.Dimension(600, 500));
        jPanel12.setName(""); // NOI18N
        jPanel12.setPreferredSize(new java.awt.Dimension(650, 500));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 36)); // NOI18N
        jLabel26.setText("AGREGAR AFILIADO");
        jPanel12.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 360, 35));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("Primer nombre:");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("Segundo Nombre:");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setText("Primer Apellido:");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setText("Segundo Apellido:");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel31.setText("Referencia:");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel32.setText("Ciudad");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel33.setText("Calle:");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel34.setText("numero casa:");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel35.setText("Avenida:");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel36.setText("Departamento:");

        javax.swing.GroupLayout InPane4Layout = new javax.swing.GroupLayout(InPane4);
        InPane4.setLayout(InPane4Layout);
        InPane4Layout.setHorizontalGroup(
            InPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InPane4Layout.createSequentialGroup()
                        .addGroup(InPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Avenida1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InPane4Layout.createSequentialGroup()
                        .addGroup(InPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(InPane4Layout.createSequentialGroup()
                                .addGroup(InPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Reff1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(InPane4Layout.createSequentialGroup()
                                .addGroup(InPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(InPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PrimerNombre1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SegundoNombre1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PrimerApellido1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SegundoApellido1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Calle1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NumCasa1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ciudad1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Depto1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(16, 16, 16))))
        );
        InPane4Layout.setVerticalGroup(
            InPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InPane4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(InPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrimerNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SegundoNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(12, 12, 12)
                .addGroup(InPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrimerApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SegundoApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(18, 18, 18)
                .addGroup(InPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Calle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(Avenida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(InPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumCasa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ciudad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Depto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(Reff1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel12.add(InPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 290, 390));

        InPane5.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel37.setText("Correo Principal:");

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel38.setText("Fecha de Nacimiento:");

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel39.setText("Correo Secundario:");

        javax.swing.GroupLayout InPane5Layout = new javax.swing.GroupLayout(InPane5);
        InPane5.setLayout(InPane5Layout);
        InPane5Layout.setHorizontalGroup(
            InPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InPane5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FechaNacimiento_cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InPane5Layout.createSequentialGroup()
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Correo4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InPane5Layout.createSequentialGroup()
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Correo3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InPane5Layout.setVerticalGroup(
            InPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InPane5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(InPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(Correo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Correo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(FechaNacimiento_cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel12.add(InPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 280, 130));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel40.setText("  Telefono:");

        AGREGAR_TELEFONO1.setText("Add");
        AGREGAR_TELEFONO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGREGAR_TELEFONO1ActionPerformed(evt);
            }
        });

        ListaTeleonos1.setModel(telefonosListModel);
        jScrollPane2.setViewportView(ListaTeleonos1);

        AGREGAR_AFILIADO_BTT1.setText("Agregar Afiliado");
        AGREGAR_AFILIADO_BTT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGREGAR_AFILIADO_BTT1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InPane6Layout = new javax.swing.GroupLayout(InPane6);
        InPane6.setLayout(InPane6Layout);
        InPane6Layout.setHorizontalGroup(
            InPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InPane6Layout.createSequentialGroup()
                .addGroup(InPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InPane6Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Telefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AGREGAR_TELEFONO1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(InPane6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(InPane6Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(AGREGAR_AFILIADO_BTT1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InPane6Layout.setVerticalGroup(
            InPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InPane6Layout.createSequentialGroup()
                .addGroup(InPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(Telefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AGREGAR_TELEFONO1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AGREGAR_AFILIADO_BTT1)
                .addGap(0, 40, Short.MAX_VALUE))
        );

        jPanel12.add(InPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 280, 240));

        jTabbedPane2.addTab("AGREGAR AFILAIDO", jPanel12);

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane2.addTab("EDITAR AFILIADO", jPanel13);

        jPanel14.setPreferredSize(new java.awt.Dimension(600, 500));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane2.addTab("ELIMINAR AFILIADO", jPanel14);

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane2.addTab("VER AFILIADO", jPanel15);

        jPanel4.add(jTabbedPane2, "card5");

        add(jPanel4, "card6");

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(600, 500));

        jPanel5.setMinimumSize(new java.awt.Dimension(600, 500));
        jPanel5.setName(""); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(650, 500));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 36)); // NOI18N
        jLabel6.setText("AGREGAR AFILIADO");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 360, 35));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Primer nombre:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Segundo Nombre:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Primer Apellido:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Segundo Apellido:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Referencia:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Ciudad");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Calle:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("numero casa:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Avenida:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Departamento:");

        javax.swing.GroupLayout InPane1Layout = new javax.swing.GroupLayout(InPane1);
        InPane1.setLayout(InPane1Layout);
        InPane1Layout.setHorizontalGroup(
            InPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InPane1Layout.createSequentialGroup()
                        .addGroup(InPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Avenida, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InPane1Layout.createSequentialGroup()
                        .addGroup(InPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(InPane1Layout.createSequentialGroup()
                                .addGroup(InPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Reff, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(InPane1Layout.createSequentialGroup()
                                .addGroup(InPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(InPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PrimerNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SegundoNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PrimerApellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SegundoApellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Calle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NumCasa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ciudad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Depto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(16, 16, 16))))
        );
        InPane1Layout.setVerticalGroup(
            InPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InPane1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(InPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(12, 12, 12)
                .addGroup(InPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(InPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Avenida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(InPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Depto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Reff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel5.add(InPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 290, 390));

        InPane2.setPreferredSize(new java.awt.Dimension(50, 50));
        InPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Correo Principal:");
        InPane2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 125, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Fecha de Nacimiento:");
        InPane2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 85, -1, -1));
        InPane2.add(Correo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 15, 127, -1));
        InPane2.add(Correo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 49, 127, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Correo Secundario:");
        InPane2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 49, 125, -1));
        InPane2.add(FechaNacimiento_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 130, 30));

        jPanel5.add(InPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 290, 120));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("  Telefono:");

        AGREGAR_TELEFONO.setText("Add");
        AGREGAR_TELEFONO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGREGAR_TELEFONOActionPerformed(evt);
            }
        });

        ListaTeleonos.setModel(telefonosListModel);
        jScrollPane1.setViewportView(ListaTeleonos);

        AGREGAR_AFILIADO_BTT.setText("Agregar Afiliado");
        AGREGAR_AFILIADO_BTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGREGAR_AFILIADO_BTTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InPane3Layout = new javax.swing.GroupLayout(InPane3);
        InPane3.setLayout(InPane3Layout);
        InPane3Layout.setHorizontalGroup(
            InPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InPane3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(AGREGAR_AFILIADO_BTT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InPane3Layout.createSequentialGroup()
                .addGroup(InPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InPane3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AGREGAR_TELEFONO, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(InPane3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)))
                .addContainerGap())
        );
        InPane3Layout.setVerticalGroup(
            InPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InPane3Layout.createSequentialGroup()
                .addGroup(InPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AGREGAR_TELEFONO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AGREGAR_AFILIADO_BTT)
                .addGap(10, 10, 10))
        );

        jPanel5.add(InPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 300, 240));

        jToggleButton1.setText("Volver Al Menu Principal");
        jToggleButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 147, 30));

        jTabbedPane1.addTab("AGREGAR AFILAIDO", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton2.setText("Volver Al Menu Principal");
        jToggleButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 140, 30));

        jTabbedPane1.addTab("EDITAR AFILIADO", jPanel6);

        jPanel7.setPreferredSize(new java.awt.Dimension(600, 500));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton3.setText("Volver Al Menu Principal");
        jToggleButton3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 140, 30));

        jTabbedPane1.addTab("ELIMINAR AFILIADO", jPanel7);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ListaAfiliados.setModel(AfiliadosListModel);
        jScrollPane3.setViewportView(ListaAfiliados);

        jPanel8.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 480, 450));

        jButton1.setText("Ver Afiliados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 120, 60));

        jToggleButton4.setText("Volver Al Menu ");
        jToggleButton4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        jPanel8.add(jToggleButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 120, 40));

        jTabbedPane1.addTab("VER AFILIADOS", jPanel8);

        add(jTabbedPane1, "card5");
    }// </editor-fold>//GEN-END:initComponents

    private void valid_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valid_userActionPerformed
        String us = user_text.getText().trim();
        System.out.println(us);
        String pass = pass_text.getText().trim();
        System.out.println(pass);

        switch (Database.validarUsuario(us, pass)) {
            case 1 -> {
                JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                CardLayout cardLayout = (CardLayout) this.getLayout();
                cardLayout.show(this, "card3");
                User_Actual = us;
            }
            case 2 -> {
                JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                CardLayout cardLayout = (CardLayout) this.getLayout();
                cardLayout.show(this, "card4");
                User_Actual = us;
            }
            default ->
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_valid_userActionPerformed

    private void GESTION_CUENTAS_BTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GESTION_CUENTAS_BTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GESTION_CUENTAS_BTTActionPerformed

    private void CERRAR_SESION_BTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CERRAR_SESION_BTTActionPerformed
        CardLayout cardLayout = (CardLayout) this.getLayout();
        cardLayout.show(this, "card2");
    }//GEN-LAST:event_CERRAR_SESION_BTTActionPerformed

    private void GESTION_PRESTAMOS_BTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GESTION_PRESTAMOS_BTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GESTION_PRESTAMOS_BTTActionPerformed

    private void GESTION_PAGOS_BTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GESTION_PAGOS_BTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GESTION_PAGOS_BTTActionPerformed

    private void CIERRA_MENSUAL_BTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CIERRA_MENSUAL_BTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CIERRA_MENSUAL_BTTActionPerformed

    private void REPORTES_BTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REPORTES_BTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REPORTES_BTTActionPerformed

    private void GESTION_AFILIADOS_BTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GESTION_AFILIADOS_BTTActionPerformed
        CardLayout cardLayout = (CardLayout) this.getLayout();
        cardLayout.show(this, "card5");
    }//GEN-LAST:event_GESTION_AFILIADOS_BTTActionPerformed

    private void CONSULTAR_CUENTASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONSULTAR_CUENTASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CONSULTAR_CUENTASActionPerformed

    private void CONSULTAR_PRESTAMOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONSULTAR_PRESTAMOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CONSULTAR_PRESTAMOSActionPerformed

    private void CONSULTAR_DIVIDENDOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONSULTAR_DIVIDENDOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CONSULTAR_DIVIDENDOSActionPerformed

    private void Informacion_personalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Informacion_personalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Informacion_personalActionPerformed

    private void CERRAR_CESION_BTT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CERRAR_CESION_BTT2ActionPerformed
        CardLayout cardLayout = (CardLayout) this.getLayout();
        cardLayout.show(this, "card3");             // TODO add your handling code here:
    }//GEN-LAST:event_CERRAR_CESION_BTT2ActionPerformed

    private void AGREGAR_TELEFONOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGREGAR_TELEFONOActionPerformed
        String telefono = Telefono.getText().trim();
        if (!telefono.isEmpty()) {
            telefonos.add(telefono);
            telefonosListModel.addElement(telefono);
            Telefono.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "El teléfono no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AGREGAR_TELEFONOActionPerformed

    private void AGREGAR_AFILIADO_BTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGREGAR_AFILIADO_BTTActionPerformed
        String primerNombre = PrimerNombre.getText().trim();
        String segundoNombre = this.SegundoNombre.getText().trim();
        String primerApellido = PrimerApellido.getText().trim();
        String segundoApellido = SegundoApellido.getText().trim();
        String calle = Calle.getText().trim();
        String avenida = Avenida.getText().trim();
        String numCasa = NumCasa.getText().trim();
        String ciudad = Ciudad.getText().trim();
        String departamento = Depto.getText().trim();
        String referencia = Reff.getText().trim();
        String correoPrimario = Correo1.getText().trim();
        String correoSecundario = Correo2.getText().trim();
        Date fechaNacimiento = FechaNacimiento_cb.getDate();

        if (primerNombre.isEmpty() || primerApellido.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El primer nombre y el primer apellido son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (telefonos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe agregar al menos un teléfono", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (calle.isEmpty() || ciudad.isEmpty() || departamento.isEmpty() || correoPrimario.isEmpty() || fechaNacimiento == null) {
            JOptionPane.showMessageDialog(this, "Todos los campos obligatorios deben estar completos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (Database.agregarAfiliado(primerNombre, segundoNombre, primerApellido, segundoApellido, calle, avenida, numCasa, ciudad, departamento, referencia, correoPrimario, correoSecundario, fechaNacimiento, telefonos, User_Actual)) {
            JOptionPane.showMessageDialog(this, "Afiliado y teléfonos agregados correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo registrar el usuario", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_AGREGAR_AFILIADO_BTTActionPerformed

    private void valid_user1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valid_user1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valid_user1ActionPerformed

    private void CERRAR_CESION_BTT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CERRAR_CESION_BTT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CERRAR_CESION_BTT1ActionPerformed

    private void GESTION_CUENTAS_BTT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GESTION_CUENTAS_BTT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GESTION_CUENTAS_BTT1ActionPerformed

    private void GESTION_AFILIADOS_BTT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GESTION_AFILIADOS_BTT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GESTION_AFILIADOS_BTT1ActionPerformed

    private void GESTION_PRESTAMOS_BTT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GESTION_PRESTAMOS_BTT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GESTION_PRESTAMOS_BTT1ActionPerformed

    private void GESTION_PAGOS_BTT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GESTION_PAGOS_BTT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GESTION_PAGOS_BTT1ActionPerformed

    private void CIERRA_MENSUAL_BTT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CIERRA_MENSUAL_BTT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CIERRA_MENSUAL_BTT1ActionPerformed

    private void REPORTES_BTT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REPORTES_BTT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REPORTES_BTT1ActionPerformed

    private void CONSULTAR_CUENTAS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONSULTAR_CUENTAS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CONSULTAR_CUENTAS1ActionPerformed

    private void CONSULTAR_PRESTAMOS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONSULTAR_PRESTAMOS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CONSULTAR_PRESTAMOS1ActionPerformed

    private void CONSULTAR_DIVIDENDOS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONSULTAR_DIVIDENDOS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CONSULTAR_DIVIDENDOS1ActionPerformed

    private void Informacion_personal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Informacion_personal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Informacion_personal1ActionPerformed

    private void CERRAR_CESION_BTT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CERRAR_CESION_BTT3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CERRAR_CESION_BTT3ActionPerformed

    private void AGREGAR_TELEFONO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGREGAR_TELEFONO1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AGREGAR_TELEFONO1ActionPerformed

    private void AGREGAR_AFILIADO_BTT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGREGAR_AFILIADO_BTT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AGREGAR_AFILIADO_BTT1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AfiliadosListModel.clear();
        try {
            AfiliadosList = Database.obtenerAfliados();
        } catch (Exception ex) {
            Logger.getLogger(Pantalla_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (Afiliados_obj afiliado : AfiliadosList) {
            AfiliadosListModel.addElement(afiliado.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        CardLayout cardLayout = (CardLayout) this.getLayout();
        cardLayout.show(this, "card3");
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        CardLayout cardLayout = (CardLayout) this.getLayout();
        cardLayout.show(this, "card3");
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        CardLayout cardLayout = (CardLayout) this.getLayout();
        cardLayout.show(this, "card3");
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        CardLayout cardLayout = (CardLayout) this.getLayout();
        cardLayout.show(this, "card3");
    }//GEN-LAST:event_jToggleButton4ActionPerformed
    private void limpiarCampos() {
        PrimerNombre.setText("");
        SegundoNombre.setText("");
        PrimerApellido.setText("");
        SegundoApellido.setText("");
        Calle.setText("");
        Avenida.setText("");
        NumCasa.setText("");
        Ciudad.setText("");
        Depto.setText("");
        Reff.setText("");
        Correo1.setText("");
        Correo2.setText("");
        FechaNacimiento_cb.setDate(null);
        telefonos.clear();
        telefonosListModel.clear();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AGREGAR_AFILIADO_BTT;
    private javax.swing.JButton AGREGAR_AFILIADO_BTT1;
    private javax.swing.JButton AGREGAR_TELEFONO;
    private javax.swing.JButton AGREGAR_TELEFONO1;
    private javax.swing.JTextField Avenida;
    private javax.swing.JTextField Avenida1;
    private javax.swing.JButton CERRAR_CESION_BTT1;
    private javax.swing.JButton CERRAR_CESION_BTT2;
    private javax.swing.JButton CERRAR_CESION_BTT3;
    private javax.swing.JButton CERRAR_SESION_BTT;
    private javax.swing.JButton CIERRA_MENSUAL_BTT;
    private javax.swing.JButton CIERRA_MENSUAL_BTT1;
    private javax.swing.JButton CONSULTAR_CUENTAS;
    private javax.swing.JButton CONSULTAR_CUENTAS1;
    private javax.swing.JButton CONSULTAR_DIVIDENDOS;
    private javax.swing.JButton CONSULTAR_DIVIDENDOS1;
    private javax.swing.JButton CONSULTAR_PRESTAMOS;
    private javax.swing.JButton CONSULTAR_PRESTAMOS1;
    private javax.swing.JTextField Calle;
    private javax.swing.JTextField Calle1;
    private javax.swing.JTextField Ciudad;
    private javax.swing.JTextField Ciudad1;
    private javax.swing.JTextField Correo1;
    private javax.swing.JTextField Correo2;
    private javax.swing.JTextField Correo3;
    private javax.swing.JTextField Correo4;
    private javax.swing.JTextField Depto;
    private javax.swing.JTextField Depto1;
    private de.wannawork.jcalendar.JCalendarComboBox FechaNacimiento_cb;
    private de.wannawork.jcalendar.JCalendarComboBox FechaNacimiento_cb1;
    private javax.swing.JButton GESTION_AFILIADOS_BTT;
    private javax.swing.JButton GESTION_AFILIADOS_BTT1;
    private javax.swing.JButton GESTION_CUENTAS_BTT;
    private javax.swing.JButton GESTION_CUENTAS_BTT1;
    private javax.swing.JButton GESTION_PAGOS_BTT;
    private javax.swing.JButton GESTION_PAGOS_BTT1;
    private javax.swing.JButton GESTION_PRESTAMOS_BTT;
    private javax.swing.JButton GESTION_PRESTAMOS_BTT1;
    private javax.swing.JPanel InPane1;
    private javax.swing.JPanel InPane2;
    private javax.swing.JPanel InPane3;
    private javax.swing.JPanel InPane4;
    private javax.swing.JPanel InPane5;
    private javax.swing.JPanel InPane6;
    private javax.swing.JButton Informacion_personal;
    private javax.swing.JButton Informacion_personal1;
    private javax.swing.JList<String> ListaAfiliados;
    private javax.swing.JList<String> ListaTeleonos;
    private javax.swing.JList<String> ListaTeleonos1;
    private javax.swing.JTextField NumCasa;
    private javax.swing.JTextField NumCasa1;
    private javax.swing.JTextField PrimerApellido;
    private javax.swing.JTextField PrimerApellido1;
    private javax.swing.JTextField PrimerNombre;
    private javax.swing.JTextField PrimerNombre1;
    private javax.swing.JButton REPORTES_BTT;
    private javax.swing.JButton REPORTES_BTT1;
    private javax.swing.JTextField Reff;
    private javax.swing.JTextField Reff1;
    private javax.swing.JTextField SegundoApellido;
    private javax.swing.JTextField SegundoApellido1;
    private javax.swing.JTextField SegundoNombre;
    private javax.swing.JTextField SegundoNombre1;
    private javax.swing.JTextField Telefono;
    private javax.swing.JTextField Telefono1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JTextField pass_text;
    private javax.swing.JTextField pass_text1;
    private javax.swing.JTextField user_text;
    private javax.swing.JTextField user_text1;
    private javax.swing.JButton valid_user;
    private javax.swing.JButton valid_user1;
    // End of variables declaration//GEN-END:variables
}
