CREATE PROCEDURE CREAR_PRESTAMOS (
    FECHA DATE,
    MONTO DECIMAL(18,2), 
    PERIODOS INTEGER,      
    SALDO DECIMAL(18,2),  
    TIPO_PRESTAMO VARCHAR(20),  
    USUARIO_CREADOR VARCHAR(30),
    AFILIADO_CODIGO VARCHAR(30))
AS
DECLARE VARIABLE v_tasa_interes DECIMAL(5,2);
DECLARE VARIABLE v_numero_prestamo VARCHAR(30);
DECLARE VARIABLE v_saldo_aportaciones DECIMAL(18,2);
DECLARE VARIABLE v_prestamo_activo INTEGER;
BEGIN

    SELECT COUNT(*) 
    FROM PRESTAMOS 
    WHERE AFILIADO_CODIGO = :AFILIADO_CODIGO AND SALDO > 0
    INTO :v_prestamo_activo;
    
    IF (v_prestamo_activo > 0) THEN
        EXCEPTION 'El afiliado ya tiene un préstamo activo.';


    IF (:PERIODOS > 12) THEN
        EXCEPTION 'El período máximo de un préstamo es de 12 meses.';


    IF (:TIPO_PRESTAMO = 'AUTOMATICO') THEN
    BEGIN
        SELECT SALDO 
        FROM CUENTA 
        WHERE AFILIADO_CODIGO = :AFILIADO_CODIGO AND TIPO_CUENTA = 'CAP'
        INTO :v_saldo_aportaciones;

        IF (:MONTO > v_saldo_aportaciones) THEN
            EXCEPTION 'El monto del préstamo automático no puede exceder el saldo de aportaciones.';

        v_tasa_interes = 10.00;
    END
    ELSE IF (:TIPO_PRESTAMO = 'FIDUCIARIO') THEN
    BEGIN
        IF (:MONTO > 10000) THEN
            EXCEPTION 'El monto máximo para préstamos fiduciarios es de L. 10,000.';
        v_tasa_interes = 15.00; 
    END
    ELSE
        EXCEPTION 'Tipo de préstamo inválido.';

    v_numero_prestamo = :AFILIADO_CODIGO || '-PT' || LPAD(NEXT VALUE FOR SEQ_PRESTAMO, 5, '0');

    INSERT INTO PRESTAMOS (
        NUMERO_PRESTAMOS, FECHA, MONTO, PERIODOS, SALDO, TASA_INTERES, TIPO_PRESTAMO,
        FECHA_CREACION, FECHA_MODIFICACION, USUARIO_CREADOR, USUARIO_MODIFICADOR, AFILIADO_CODIGO
    ) VALUES (
        :v_numero_prestamo, :FECHA, :MONTO, :PERIODOS, :SALDO, :v_tasa_interes, :TIPO_PRESTAMO,
        CURRENT_DATE, CURRENT_DATE, :USUARIO_CREADOR, :USUARIO_CREADOR, :AFILIADO_CODIGO
    );
END;


CREATE PROCEDURE LEER_PRESTAMO (
    NUMERO_PRESTAMO VARCHAR(30))
RETURNS (
    FECHA DATE,
    MONTO DECIMAL(18, 2),
    PERIODOS INTEGER,
    SALDO DECIMAL(18, 2),
    TASA_INTERES DECIMAL(5, 2),
    TIPO_PRESTAMO VARCHAR(20),
    FECHA_CREACION DATE,
    FECHA_MODIFICACION DATE,
    USUARIO_CREADOR VARCHAR(30),
    USUARIO_MODIFICADOR VARCHAR(30),
    AFILIADO_CODIGO VARCHAR(30))
AS
BEGIN
    FOR SELECT FECHA, MONTO, PERIODOS, SALDO, TASA_INTERES, TIPO_PRESTAMO,
              FECHA_CREACION, FECHA_MODIFICACION, USUARIO_CREADOR, USUARIO_MODIFICADOR, AFILIADO_CODIGO
        FROM PRESTAMOS
        WHERE NUMERO_PRESTAMO = :NUMERO_PRESTAMO
        INTO :FECHA, :MONTO, :PERIODOS, :SALDO, :TASA_INTERES, :TIPO_PRESTAMO,
             :FECHA_CREACION, :FECHA_MODIFICACION, :USUARIO_CREADOR, :USUARIO_MODIFICADOR, :AFILIADO_CODIGO
    DO
        SUSPEND;
END;

CREATE PROCEDURE ACTUALIZAR_PRESTAMO (
    NUMERO_PRESTAMO VARCHAR(30),
    FECHA DATE,
    MONTO DECIMAL(18, 2),
    PERIODOS INTEGER,
    SALDO DECIMAL(18, 2),
    TASA_INTERES DECIMAL(5, 2),
    TIPO_PRESTAMO VARCHAR(20),
    USUARIO_MODIFICADOR VARCHAR(30))
AS
BEGIN
    UPDATE PRESTAMOS
    SET FECHA = :FECHA,
        MONTO = :MONTO,
        PERIODOS = :PERIODOS,
        SALDO = :SALDO,
        TASA_INTERES = :TASA_INTERES,
        TIPO_PRESTAMO = :TIPO_PRESTAMO,
        FECHA_MODIFICACION = CURRENT_DATE,
        USUARIO_MODIFICADOR = :USUARIO_MODIFICADOR
    WHERE NUMERO_PRESTAMO = :NUMERO_PRESTAMO;
END;

CREATE PROCEDURE ELIMINAR_PRESTAMO (
    NUMERO_PRESTAMO VARCHAR(30))
AS
BEGIN
    DELETE FROM PRESTAMOS
    WHERE NUMERO_PRESTAMO = :NUMERO_PRESTAMO;
END;