
CREATE TABLE AFILIADO (
    CODIGO VARCHAR(30) NOT NULL PRIMARY KEY,
    PRIMER_NOMBRE VARCHAR(50),
    SEGUNDO_NOMBRE VARCHAR(50),
    PRIMER_APELLIDO VARCHAR(50),
    SEGUNDO_APELLIDO VARCHAR(50),
    CALLE VARCHAR(50),
    AVENIDA VARCHAR(50),
    NUM_CASA VARCHAR(10),
    CIUDAD VARCHAR(50),
    DEPARTAMENTO VARCHAR(50),
    REFERENCIA VARCHAR(50),
    CORREO_PRIMARIO VARCHAR(50) NOT NULL,
    CORREO_SECUNDARIO VARCHAR(50),
    FECHA_NACIMIENTO DATE,
    FECHA_INICIO DATE,
    FECHA_CREACION_DATOS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ULTIMA_ACTUALIZACION TIMESTAMP,
    USUARIO_CREADOR VARCHAR(30),
    ULTIMO_EDITOR VARCHAR(30)
);


CREATE TABLE PRESTAMOS (
    NUMERO_PRESTAMO VARCHAR(30) NOT NULL PRIMARY KEY,
    FECHA DATE,
    MONTO DECIMAL(18, 2), 
    PERIODOS INTEGER,      
    SALDO DECIMAL(18, 2),  
    TASA_INTERES DECIMAL(5, 2), 
    TIPO_PRESTAMO VARCHAR(20),  
    FECHA_CREACION DATE,
    FECHA_MODIFICACION DATE,
    USUARIO_CREADOR VARCHAR(30),
    USUARIO_MODIFICADOR VARCHAR(30),
    AFILIADO_CODIGO VARCHAR(30),
    FOREIGN KEY (AFILIADO_CODIGO) REFERENCES AFILIADO(CODIGO)
);


CREATE TABLE TELEFONOS_AFILIADO (
    TELEFONO VARCHAR(30) NOT NULL,
    AFILIADO_CODIGO VARCHAR(30) NOT NULL,
    PRIMARY KEY (TELEFONO, AFILIADO_CODIGO),
    FOREIGN KEY (AFILIADO_CODIGO) REFERENCES AFILIADO(CODIGO)
);




CREATE TABLE CUENTA (
    NUMERO_CUENTA VARCHAR(30) NOT NULL PRIMARY KEY,
    TIPO_CUENTA CHAR(3) NOT NULL,
    INGRESADO_MES INTEGER,  
    SALDO DECIMAL(18, 2),   
    FECHA_APERTURA DATE,
    FECHA_CREACION DATE,
    FECHA_ULTIMA_MODIFICACION DATE,
    USUARIO_CREADOR VARCHAR(30),
    ULTIMO_EDITOR VARCHAR(30),
    AFILIADO_CODIGO VARCHAR(30),
    FOREIGN KEY (AFILIADO_CODIGO) REFERENCES AFILIADO(CODIGO)
);


CREATE TABLE USUARIO (
    ID_USUARIO VARCHAR(30) NOT NULL PRIMARY KEY,
    CONTRASENA VARCHAR(50),
    AFILIADO_CODIGO VARCHAR(30),
    ROL VARCHAR(30),
    FOREIGN KEY (AFILIADO_CODIGO) REFERENCES AFILIADO(CODIGO)
);


CREATE TABLE PAGOS (
    NUMERO_PAGO VARCHAR(30) NOT NULL,
	NUMERO_PRESTAMOS VARCHAR(30) NOT NULL,
    FECHA DATE,
    MONTO DECIMAL(18, 2), 
    INTERESES_PAGADOS DECIMAL(18, 2),  
    CAPITAL_PAGADO DECIMAL(18, 2),  
    PRIMARY KEY (NUMERO_PAGO, NUMERO_PRESTAMOS),
    FOREIGN KEY (NUMERO_PRESTAMOS) REFERENCES PRESTAMOS(NUMERO_PRESTAMOS)
);


CREATE TABLE LIQUIDACION (
    ID_LIQUIDACION VARCHAR(30) NOT NULL PRIMARY KEY,
    TIPO_LIQUIDACION CHAR(1),
    FECHA_LIQUIDACION DATE,
    AFILIADO_CODIGO VARCHAR(30),
    FOREIGN KEY (AFILIADO_CODIGO) REFERENCES AFILIADO(CODIGO)
);


CREATE TABLE PAGO_LIQUIDACION (
    NUMERO_PAGO VARCHAR(30) NOT NULL,
    NUMERO_PRESTAMOS VARCHAR(30) NOT NULL,
    ID_LIQUIDACION VARCHAR(30) NOT NULL,
    PRIMARY KEY (NUMERO_PAGO, NUMERO_PRESTAMOS, ID_LIQUIDACION),
    FOREIGN KEY (NUMERO_PAGO, NUMERO_PRESTAMOS) REFERENCES PAGOS(NUMERO_PAGO, NUMERO_PRESTAMOS),
    FOREIGN KEY (ID_LIQUIDACION) REFERENCES LIQUIDACION(ID_LIQUIDACION)
);


CREATE TABLE CIERRES (
    ID_CIERRE VARCHAR(30) NOT NULL PRIMARY KEY,
    FECHA DATE,
    DESCRIPCION VARCHAR(50)
);


CREATE TABLE CIERRES_PAGOS (
    NUMERO_PAGO VARCHAR(30) NOT NULL,
    NUMERO_PRESTAMOS  VARCHAR(30) NOT NULL,
   	ID_CIERRE VARCHAR(30) NOT NULL,
    PRIMARY KEY (NUMERO_PAGO, NUMERO_PRESTAMOS,ID_CIERRE),
    FOREIGN KEY (NUMERO_PAGO, NUMERO_PRESTAMOS) REFERENCES PAGOS(NUMERO_PAGO, NUMERO_PRESTAMOS),
    FOREIGN KEY (ID_CIERRE) REFERENCES CIERRES(ID_CIERRE)
);


CREATE TABLE CIERRE_TRANSACCION (
    NUMERO_TRANSACCION VARCHAR(30) NOT NULL,
    NUMERO_CUENTA VARCHAR(30) NOT NULL,
    ID_CIERRE VARCHAR(30) NOT NULL,
    PRIMARY KEY (NUMERO_TRANSACCION, NUMERO_CUENTA),
    FOREIGN KEY (NUMERO_TRANSACCION, NUMERO_CUENTA) REFERENCES TRANSACCION(NUMERO_TRANSACCION, NUMERO_CUENTA),
    FOREIGN KEY (ID_CIERRE) REFERENCES CIERRES(ID_CIERRE)
);


CREATE TABLE TRANSACCION (
    NUMERO_TRANSACCION VARCHAR(30) NOT NULL,
    NUMERO_CUENTA VARCHAR(30) NOT NULL,
    FECHA DATE,
    MONTO DECIMAL(18, 2),  
    COMENTARIO VARCHAR(50),
    TIPO_TRANSACCION CHAR(1),
    PRIMARY KEY (NUMERO_TRANSACCION, NUMERO_CUENTA),
    FOREIGN KEY (NUMERO_CUENTA) REFERENCES CUENTA(NUMERO_CUENTA)
);


CREATE TABLE LIQUIDACION_TRANSACCION (
    ID_TRANSACCION VARCHAR(30) NOT NULL PRIMARY KEY,
    ID_CIERRE VARCHAR(30),
    ID_LIQUIDACION VARCHAR(30),
    FOREIGN KEY (ID_CIERRE) REFERENCES CIERRES(ID_CIERRE),
    FOREIGN KEY (ID_LIQUIDACION) REFERENCES LIQUIDACION(ID_LIQUIDACION)
);


CREATE TABLE DIVIDENDO_USUARIO (
    ID_USUARIO VARCHAR(30) NOT NULL PRIMARY KEY,
    SUBTOTAL_GANANCIA DECIMAL(18, 2),  
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);


CREATE TABLE DIVIDENDOS_MES (
    ID_CIERRE VARCHAR(30) NOT NULL,
    ID_USUARIO VARCHAR(30) NOT NULL ,
    SALDO_CUENTA_AHORRO DECIMAL(18, 2), 
    TOTAL_INTERESES_PRESTAMO DECIMAL(18, 2),  
    PORCENTAJE_GANANCIA DECIMAL(5, 2), 
    TOTAL_GANANCIA DECIMAL(18, 2),  
    PRIMARY KEY (ID_CIERRE, ID_USUARIO),
    FOREIGN KEY (ID_CIERRE) REFERENCES CIERRES(ID_CIERRE),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);